/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author GIGABYTE
 */
public class ConfigCambiarTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form ConfigCambiarTarjeta
     */
    public ConfigCambiarTarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        lblCorreo1 = new javax.swing.JLabel();
        lblCorreo3 = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtNumTarjet = new javax.swing.JTextField();
        cbxMedioPago = new javax.swing.JComboBox<>();
        lblCorreo4 = new javax.swing.JLabel();
        lblCorreo5 = new javax.swing.JLabel();
        dcFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtCvv = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(159, 162, 178));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(121, 127, 139));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setBackground(new java.awt.Color(121, 127, 139));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atrasBoton.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        lblCorreo1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblCorreo1.setText("Medio de pago:");
        jPanel1.add(lblCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        lblCorreo3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblCorreo3.setText("Fecha de vencimiento:");
        jPanel1.add(lblCorreo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 30));

        btnCambiar.setBackground(new java.awt.Color(22, 38, 46));
        btnCambiar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCambiar.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiar.setText("Cambiar tarjeta");
        jPanel1.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 190, 50));

        jPanel4.setBackground(new java.awt.Color(159, 162, 178));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 670, 40));

        txtNumTarjet.setBackground(new java.awt.Color(121, 127, 139));
        txtNumTarjet.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNumTarjet.setBorder(null);
        txtNumTarjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumTarjetActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumTarjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 260, 30));

        cbxMedioPago.setBackground(new java.awt.Color(121, 127, 139));
        cbxMedioPago.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxMedioPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                                  ", "Visa (Crédito o débito)", "Master Card (Crédito o débito)", "American Express (Crédito)", "Diners Club (Crédito)", " " }));
        cbxMedioPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cbxMedioPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 280, -1));

        lblCorreo4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblCorreo4.setText("Número de tarjeta:");
        jPanel1.add(lblCorreo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        lblCorreo5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblCorreo5.setText("CVV:");
        jPanel1.add(lblCorreo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));
        jPanel1.add(dcFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 260, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 260, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 260, 10));

        txtCvv.setBackground(new java.awt.Color(121, 127, 139));
        txtCvv.setBorder(null);
        jPanel1.add(txtCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumTarjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumTarjetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumTarjetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigCambiarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigCambiarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigCambiarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigCambiarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigCambiarTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnCambiar;
    public javax.swing.JComboBox<String> cbxMedioPago;
    public com.toedter.calendar.JDateChooser dcFechaVencimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblCorreo3;
    private javax.swing.JLabel lblCorreo4;
    private javax.swing.JLabel lblCorreo5;
    public javax.swing.JTextField txtCvv;
    public javax.swing.JTextField txtNumTarjet;
    // End of variables declaration//GEN-END:variables
}
