/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Yesenia
 */
public class frmBoleta extends javax.swing.JFrame {

    /** Creates new form frmBoleta */
    public frmBoleta() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PTituloConfiguracion = new javax.swing.JPanel();
        lblBoletaPago = new javax.swing.JLabel();
        lblBoletaConsumo = new javax.swing.JLabel();
        lblBoletaRecarga = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblEstacion = new javax.swing.JLabel();
        lblVehiculo = new javax.swing.JLabel();
        lblNumDoc = new javax.swing.JLabel();
        btnOKBoleta = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtNumDoc = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtVehiculo = new javax.swing.JTextField();
        txtEstacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PTituloConfiguracion.setBackground(new java.awt.Color(159, 162, 178));
        PTituloConfiguracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBoletaPago.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        lblBoletaPago.setForeground(new java.awt.Color(0, 0, 0));
        lblBoletaPago.setText("Boleta de pago PEX");
        PTituloConfiguracion.add(lblBoletaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        lblBoletaConsumo.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        lblBoletaConsumo.setForeground(new java.awt.Color(0, 0, 0));
        lblBoletaConsumo.setText("Boleta de consumo PEX");
        PTituloConfiguracion.add(lblBoletaConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        lblBoletaRecarga.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        lblBoletaRecarga.setForeground(new java.awt.Color(0, 0, 0));
        lblBoletaRecarga.setText("Boleta de recarga PEX");
        PTituloConfiguracion.add(lblBoletaRecarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel1.add(PTituloConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 70));

        jPanel2.setBackground(new java.awt.Color(121, 127, 139));

        lblUsuario.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Usuario:");

        lblMonto.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(0, 0, 0));
        lblMonto.setText("Monto:");

        lblFecha.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha:");

        lblEstacion.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblEstacion.setForeground(new java.awt.Color(0, 0, 0));
        lblEstacion.setText("Estación:");

        lblVehiculo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        lblVehiculo.setText("Vehiculo:");

        lblNumDoc.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblNumDoc.setForeground(new java.awt.Color(0, 0, 0));
        lblNumDoc.setText("N° documento:");

        btnOKBoleta.setBackground(new java.awt.Color(22, 38, 46));
        btnOKBoleta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnOKBoleta.setForeground(new java.awt.Color(255, 255, 255));
        btnOKBoleta.setText("OK");
        btnOKBoleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(121, 127, 139));
        txtUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtUsuario.setBorder(null);

        txtNumDoc.setEditable(false);
        txtNumDoc.setBackground(new java.awt.Color(121, 127, 139));
        txtNumDoc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNumDoc.setBorder(null);

        txtMonto.setEditable(false);
        txtMonto.setBackground(new java.awt.Color(121, 127, 139));
        txtMonto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMonto.setBorder(null);
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(121, 127, 139));
        txtFecha.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtFecha.setBorder(null);

        txtVehiculo.setEditable(false);
        txtVehiculo.setBackground(new java.awt.Color(121, 127, 139));
        txtVehiculo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtVehiculo.setBorder(null);

        txtEstacion.setEditable(false);
        txtEstacion.setBackground(new java.awt.Color(121, 127, 139));
        txtEstacion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtEstacion.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("S/");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(62, 62, 62)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lblUsuario)
                    .add(lblMonto)
                    .add(lblFecha)
                    .add(lblEstacion)
                    .add(lblVehiculo)
                    .add(lblNumDoc))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtMonto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(txtNumDoc)
                        .add(txtFecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(txtVehiculo)
                        .add(txtEstacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 221, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(txtUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnOKBoleta)
                .add(210, 210, 210))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblUsuario)
                    .add(txtUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblNumDoc)
                    .add(txtNumDoc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(29, 29, 29)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblMonto)
                    .add(txtMonto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .add(29, 29, 29)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblFecha)
                    .add(txtFecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(29, 29, 29)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblEstacion)
                    .add(txtEstacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(29, 29, 29)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblVehiculo)
                    .add(txtVehiculo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(btnOKBoleta)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 510, 400));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBoleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PTituloConfiguracion;
    public javax.swing.JButton btnOKBoleta;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblBoletaConsumo;
    public javax.swing.JLabel lblBoletaPago;
    public javax.swing.JLabel lblBoletaRecarga;
    public javax.swing.JLabel lblEstacion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNumDoc;
    private javax.swing.JLabel lblUsuario;
    public javax.swing.JLabel lblVehiculo;
    public javax.swing.JTextField txtEstacion;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtMonto;
    public javax.swing.JTextField txtNumDoc;
    public javax.swing.JTextField txtUsuario;
    public javax.swing.JTextField txtVehiculo;
    // End of variables declaration//GEN-END:variables

}
