/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Yesenia
 */
public class frmEntrega extends javax.swing.JFrame {

    /** Creates new form frmEntrega */
    public frmEntrega() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PGeneralEntrega = new javax.swing.JPanel();
        PTituloEntrega = new javax.swing.JPanel();
        txtTituloEntrega = new javax.swing.JLabel();
        PContenidoEntrega = new javax.swing.JPanel();
        lblIconEntrega = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextPane();
        lblDepartamento = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        lblProvincia = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        lblAvenida = new javax.swing.JLabel();
        txtAvenida = new javax.swing.JTextField();
        lblDistrito = new javax.swing.JLabel();
        cbxDistrito = new javax.swing.JComboBox<>();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblTeleforno = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblReferencia = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        btnSiguiente3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PGeneralEntrega.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PTituloEntrega.setBackground(new java.awt.Color(159, 162, 178));
        PTituloEntrega.setPreferredSize(new java.awt.Dimension(680, 110));

        txtTituloEntrega.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        txtTituloEntrega.setForeground(new java.awt.Color(0, 0, 0));
        txtTituloEntrega.setText("Datos de entrega");

        org.jdesktop.layout.GroupLayout PTituloEntregaLayout = new org.jdesktop.layout.GroupLayout(PTituloEntrega);
        PTituloEntrega.setLayout(PTituloEntregaLayout);
        PTituloEntregaLayout.setHorizontalGroup(
            PTituloEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PTituloEntregaLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .add(txtTituloEntrega, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 371, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(139, 139, 139))
        );
        PTituloEntregaLayout.setVerticalGroup(
            PTituloEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PTituloEntregaLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .add(txtTituloEntrega)
                .add(28, 28, 28))
        );

        PGeneralEntrega.add(PTituloEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PContenidoEntrega.setBackground(new java.awt.Color(121, 127, 139));

        lblIconEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entrega.png"))); // NOI18N

        txtDescripcion.setBackground(new java.awt.Color(121, 127, 139));
        txtDescripcion.setBorder(null);
        txtDescripcion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtDescripcion.setText("La entrega de tu PEX es gratuita y dentro de los 7 días hábiles. Recuerda que debe recibirlo una persona que pueda firmar un cargo de recepción. ");
        txtDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(txtDescripcion);

        lblDepartamento.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        lblDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        lblDepartamento.setText("Departamento:");

        txtDepartamento.setBackground(new java.awt.Color(121, 127, 139));
        txtDepartamento.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        txtDepartamento.setBorder(null);

        lblProvincia.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        lblProvincia.setForeground(new java.awt.Color(0, 0, 0));
        lblProvincia.setText("Provincia:");

        txtProvincia.setBackground(new java.awt.Color(121, 127, 139));
        txtProvincia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtProvincia.setForeground(new java.awt.Color(0, 0, 0));
        txtProvincia.setBorder(null);

        lblAvenida.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        lblAvenida.setForeground(new java.awt.Color(0, 0, 0));
        lblAvenida.setText("Calle, Jirón, Avenida:");

        txtAvenida.setBackground(new java.awt.Color(121, 127, 139));
        txtAvenida.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAvenida.setForeground(new java.awt.Color(0, 0, 0));
        txtAvenida.setBorder(null);

        lblDistrito.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        lblDistrito.setForeground(new java.awt.Color(0, 0, 0));
        lblDistrito.setText("Distrito:");

        cbxDistrito.setBackground(new java.awt.Color(121, 127, 139));
        cbxDistrito.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxDistrito.setForeground(new java.awt.Color(0, 0, 0));
        cbxDistrito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                                                           ", "ANCON", "ATE", "BARRANCO", "BELLAVISTA", "BREÑA", "CARABAYLLO", "CARMEN DE LA LEGUA REYNOSO", "CHACLACAYO", "CHORRILLOS", "CIENEGUILLA", "COMAS", "EL AGUSTINO", "INDEPENDENCIA", "JESUS MARIA", "LA MOLINA", "LA PERLA", "LA PUNTA", "LA VICTORIA", "LIMA", "LINCE", "LOS OLIVOS", "LURIGANCHO", "LURIN", "MAGDALENA DEL MAR", "MIRAFLORES", "PACHACAMAC", "PUCUSANA", "PUEBLO LIBRE", "PUENTE PIEDRA", "PUNTA HERMOSA", "PUNTA NEGRA", "RIMAC", "SAN BARTOLO", "SAN BORJA", "SAN ISIDRO", "SAN JUAN DE LURIGANCHO", "SAN JUAN DE MIRAFLORES", "SAN LUIS", "SAN MARTIN DE PORRES", "SAN MIGUEL", "SANTA ANITA", "SANTA MARIA DEL MAR", "SANTA ROSA", "SANTIAGO DE SURCO", "SURQUILLO", "VENTANILLA", "VILLA EL SALVADOR", "VILLA MARIA DEL TRIUNFO" }));
        cbxDistrito.setBorder(null);
        cbxDistrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblNumero.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(0, 0, 0));
        lblNumero.setText("Número:");

        txtNumero.setBackground(new java.awt.Color(121, 127, 139));
        txtNumero.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(0, 0, 0));
        txtNumero.setBorder(null);

        lblTeleforno.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        lblTeleforno.setForeground(new java.awt.Color(0, 0, 0));
        lblTeleforno.setText("Teléfono de contacto:");

        txtTelefono.setBackground(new java.awt.Color(121, 127, 139));
        txtTelefono.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setBorder(null);

        lblReferencia.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        lblReferencia.setForeground(new java.awt.Color(0, 0, 0));
        lblReferencia.setText("Referencia:");

        txtReferencia.setBackground(new java.awt.Color(121, 127, 139));
        txtReferencia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtReferencia.setForeground(new java.awt.Color(0, 0, 0));
        txtReferencia.setBorder(null);

        btnSiguiente3.setBackground(new java.awt.Color(121, 127, 139));
        btnSiguiente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/siguienteBoton.png"))); // NOI18N
        btnSiguiente3.setBorder(null);
        btnSiguiente3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        org.jdesktop.layout.GroupLayout PContenidoEntregaLayout = new org.jdesktop.layout.GroupLayout(PContenidoEntrega);
        PContenidoEntrega.setLayout(PContenidoEntregaLayout);
        PContenidoEntregaLayout.setHorizontalGroup(
            PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PContenidoEntregaLayout.createSequentialGroup()
                .add(65, 65, 65)
                .add(lblIconEntrega, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 444, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoEntregaLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoEntregaLayout.createSequentialGroup()
                        .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator4)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, txtReferencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 589, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(jSeparator6)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, lblDepartamento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(txtDepartamento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(PContenidoEntregaLayout.createSequentialGroup()
                                .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(jSeparator1)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, lblAvenida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(txtAvenida, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                                    .add(lblNumero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(txtNumero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(28, 28, 28)
                                .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblTeleforno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(txtTelefono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jSeparator5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(lblDistrito, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(cbxDistrito, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(jSeparator2))
                                    .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(jSeparator7)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, lblProvincia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(txtProvincia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(lblReferencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(38, 38, 38))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoEntregaLayout.createSequentialGroup()
                        .add(btnSiguiente3)
                        .add(26, 26, 26))))
        );
        PContenidoEntregaLayout.setVerticalGroup(
            PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PContenidoEntregaLayout.createSequentialGroup()
                .add(38, 38, 38)
                .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lblIconEntrega)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoEntregaLayout.createSequentialGroup()
                        .add(lblDepartamento)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtDepartamento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoEntregaLayout.createSequentialGroup()
                        .add(lblProvincia)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtProvincia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblAvenida)
                    .add(lblDistrito))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtAvenida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cbxDistrito, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(PContenidoEntregaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(PContenidoEntregaLayout.createSequentialGroup()
                        .add(lblNumero)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtNumero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(PContenidoEntregaLayout.createSequentialGroup()
                        .add(lblTeleforno)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtTelefono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblReferencia)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtReferencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnSiguiente3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PGeneralEntrega.add(PContenidoEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 680, 510));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralEntrega, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralEntrega, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEntrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEntrega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PContenidoEntrega;
    private javax.swing.JPanel PGeneralEntrega;
    private javax.swing.JPanel PTituloEntrega;
    public javax.swing.JButton btnSiguiente3;
    public javax.swing.JComboBox<String> cbxDistrito;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblAvenida;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblDistrito;
    private javax.swing.JLabel lblIconEntrega;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JLabel lblTeleforno;
    public javax.swing.JTextField txtAvenida;
    public javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextPane txtDescripcion;
    public javax.swing.JTextField txtNumero;
    public javax.swing.JTextField txtProvincia;
    public javax.swing.JTextField txtReferencia;
    public javax.swing.JTextField txtTelefono;
    private javax.swing.JLabel txtTituloEntrega;
    // End of variables declaration//GEN-END:variables

}
