/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;


public class frmLogin extends javax.swing.JFrame {


    public frmLogin() {
        initComponents();
        OjoCerrado.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PGeneralLogin = new javax.swing.JPanel();
        lblTituloLogin = new javax.swing.JLabel();
        PContenidoLogin = new javax.swing.JPanel();
        lblUsuarioLogin = new javax.swing.JLabel();
        txtUsuarioLogin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblContraseñaLogin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionLogin = new javax.swing.JTextPane();
        btnIniciarSesion = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        txtContrasena = new javax.swing.JPasswordField();
        OjoCerrado = new javax.swing.JLabel();
        OjoAbierto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PGeneralLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoPex.png"))); // NOI18N
        PGeneralLogin.add(lblTituloLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, -1));

        PContenidoLogin.setBackground(new java.awt.Color(121, 127, 139));
        PContenidoLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuarioLogin.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblUsuarioLogin.setText("Correo:");
        PContenidoLogin.add(lblUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        txtUsuarioLogin.setBackground(new java.awt.Color(121, 127, 139));
        txtUsuarioLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtUsuarioLogin.setBorder(null);
        PContenidoLogin.add(txtUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 45, 216, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        PContenidoLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 216, 10));

        lblContraseñaLogin.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblContraseñaLogin.setText("Contraseña:");
        PContenidoLogin.add(lblContraseñaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 40));

        txtDescripcionLogin.setEditable(false);
        txtDescripcionLogin.setBackground(new java.awt.Color(121, 127, 139));
        txtDescripcionLogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDescripcionLogin.setText("IMPORTANTE\nUsuario: Ingrese su DNI, RUC o correo electrónico.\nSi está ingresando por primera vez su Usuario y Contraseña (provisional) es el número de documento de identidad con el cual se ha registrado en PEX.");
        jScrollPane1.setViewportView(txtDescripcionLogin);

        PContenidoLogin.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 386, -1));

        btnIniciarSesion.setBackground(new java.awt.Color(22, 38, 46));
        btnIniciarSesion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar sesión");
        PContenidoLogin.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 316, -1, 37));

        btnAtras.setBackground(new java.awt.Color(121, 127, 139));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atrasBoton.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PContenidoLogin.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 316, -1, -1));
        PContenidoLogin.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 124, 213, 30));

        OjoCerrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ocultar_32px.png"))); // NOI18N
        OjoCerrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OjoCerrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OjoCerradoMouseClicked(evt);
            }
        });
        PContenidoLogin.add(OjoCerrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 30, 40));

        OjoAbierto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver_32px.png"))); // NOI18N
        OjoAbierto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OjoAbierto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OjoAbiertoMouseClicked(evt);
            }
        });
        PContenidoLogin.add(OjoAbierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 30, 40));

        PGeneralLogin.add(PContenidoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 540, 390));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralLogin, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralLogin, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OjoCerradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OjoCerradoMouseClicked

        OjoAbierto.setVisible(true);
        OjoCerrado.setVisible(false);
txtContrasena.setEchoChar('•');
    }//GEN-LAST:event_OjoCerradoMouseClicked

    private void OjoAbiertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OjoAbiertoMouseClicked
        OjoAbierto.setVisible(false);
        OjoCerrado.setVisible(true);
        txtContrasena.setEchoChar((char) 0);
    }//GEN-LAST:event_OjoAbiertoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel OjoAbierto;
    public javax.swing.JLabel OjoCerrado;
    private javax.swing.JPanel PContenidoLogin;
    private javax.swing.JPanel PGeneralLogin;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnIniciarSesion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblContraseñaLogin;
    private javax.swing.JLabel lblTituloLogin;
    private javax.swing.JLabel lblUsuarioLogin;
    public javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextPane txtDescripcionLogin;
    public javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables

}
