/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Yesenia
 */
public class frmMovimientos extends javax.swing.JFrame {

    /** Creates new form frmMovimientos */
    public frmMovimientos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PGeneralMovimientos = new javax.swing.JPanel();
        PTituloMovimientos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PContenidoMovimientos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMovimientos = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        btnAZ = new javax.swing.JButton();
        btnZA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PGeneralMovimientos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PTituloMovimientos.setBackground(new java.awt.Color(159, 162, 178));

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabel2.setText("Movimientos de cuenta");

        org.jdesktop.layout.GroupLayout PTituloMovimientosLayout = new org.jdesktop.layout.GroupLayout(PTituloMovimientos);
        PTituloMovimientos.setLayout(PTituloMovimientosLayout);
        PTituloMovimientosLayout.setHorizontalGroup(
            PTituloMovimientosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PTituloMovimientosLayout.createSequentialGroup()
                .add(107, 107, 107)
                .add(jLabel2)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        PTituloMovimientosLayout.setVerticalGroup(
            PTituloMovimientosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PTituloMovimientosLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        PGeneralMovimientos.add(PTituloMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PContenidoMovimientos.setBackground(new java.awt.Color(121, 127, 139));

        jMovimientos.setBackground(new java.awt.Color(121, 127, 153));
        jMovimientos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Tipo", "Monto", "Vehículo", "Peaje", "Estación"
            }
        ));
        jScrollPane1.setViewportView(jMovimientos);

        btnAtras.setBackground(new java.awt.Color(121, 127, 139));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atrasBoton.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAZ.setBackground(new java.awt.Color(159, 162, 178));
        btnAZ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAZ.setText("A->Z");
        btnAZ.setToolTipText("");
        btnAZ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAZ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAZActionPerformed(evt);
            }
        });

        btnZA.setBackground(new java.awt.Color(159, 162, 178));
        btnZA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnZA.setText("Z->A");
        btnZA.setToolTipText("");
        btnZA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnZA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZAActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PContenidoMovimientosLayout = new org.jdesktop.layout.GroupLayout(PContenidoMovimientos);
        PContenidoMovimientos.setLayout(PContenidoMovimientosLayout);
        PContenidoMovimientosLayout.setHorizontalGroup(
            PContenidoMovimientosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PContenidoMovimientosLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 555, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(PContenidoMovimientosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PContenidoMovimientosLayout.createSequentialGroup()
                        .add(43, 43, 43)
                        .add(btnAtras))
                    .add(PContenidoMovimientosLayout.createSequentialGroup()
                        .add(46, 46, 46)
                        .add(PContenidoMovimientosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btnAZ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btnZA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        PContenidoMovimientosLayout.setVerticalGroup(
            PContenidoMovimientosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoMovimientosLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .add(PContenidoMovimientosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoMovimientosLayout.createSequentialGroup()
                        .add(btnAZ)
                        .add(56, 56, 56)
                        .add(btnZA)
                        .add(125, 125, 125)
                        .add(btnAtras)
                        .add(26, 26, 26))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoMovimientosLayout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 401, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18))))
        );

        PGeneralMovimientos.add(PContenidoMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, 710, 460));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralMovimientos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralMovimientos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAZActionPerformed

    private void btnZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnZAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMovimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PContenidoMovimientos;
    private javax.swing.JPanel PGeneralMovimientos;
    private javax.swing.JPanel PTituloMovimientos;
    public javax.swing.JButton btnAZ;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnZA;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTable jMovimientos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
