/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Yesenia
 */
public class frmOpcionesIngreso extends javax.swing.JFrame {

    /** Creates new form frmOpcionesIngreso */
    public frmOpcionesIngreso() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PGeneralOpciones = new javax.swing.JPanel();
        PTituloOpciones = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        PContenidoOpciones = new javax.swing.JPanel();
        btnRecargar = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();
        btnMovimientos = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PGeneralOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PTituloOpciones.setBackground(new java.awt.Color(159, 162, 178));

        lblBienvenido.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblBienvenido.setText("¡Bienvenido a tu cuenta PEX!");

        lblUsuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblUsuario.setText("Usuario:");

        txtNombreUsuario.setBackground(new java.awt.Color(159, 162, 178));
        txtNombreUsuario.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtNombreUsuario.setBorder(null);

        org.jdesktop.layout.GroupLayout PTituloOpcionesLayout = new org.jdesktop.layout.GroupLayout(PTituloOpciones);
        PTituloOpciones.setLayout(PTituloOpcionesLayout);
        PTituloOpcionesLayout.setHorizontalGroup(
            PTituloOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PTituloOpcionesLayout.createSequentialGroup()
                .add(54, 54, 54)
                .add(lblUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtNombreUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 263, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PTituloOpcionesLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lblBienvenido)
                .add(79, 79, 79))
        );
        PTituloOpcionesLayout.setVerticalGroup(
            PTituloOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PTituloOpcionesLayout.createSequentialGroup()
                .add(15, 15, 15)
                .add(lblBienvenido)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(PTituloOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblUsuario)
                    .add(txtNombreUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        PGeneralOpciones.add(PTituloOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 90));

        PContenidoOpciones.setBackground(new java.awt.Color(121, 127, 139));

        btnRecargar.setBackground(new java.awt.Color(22, 38, 46));
        btnRecargar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRecargar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecargar.setText("Recargar PEX");
        btnRecargar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRecargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnSaldo.setBackground(new java.awt.Color(22, 38, 46));
        btnSaldo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSaldo.setForeground(new java.awt.Color(255, 255, 255));
        btnSaldo.setText("Consultar saldo");
        btnSaldo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnMovimientos.setBackground(new java.awt.Color(22, 38, 46));
        btnMovimientos.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        btnMovimientos.setText("Consultar movimientos");
        btnMovimientos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnVehiculos.setBackground(new java.awt.Color(22, 38, 46));
        btnVehiculos.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnVehiculos.setText("Vehículos afiliados");
        btnVehiculos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnPagar.setBackground(new java.awt.Color(22, 38, 46));
        btnPagar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setText("Pagar peaje");
        btnPagar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnConfiguracion.setBackground(new java.awt.Color(22, 38, 46));
        btnConfiguracion.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        btnConfiguracion.setText("Configuración de la cuenta");
        btnConfiguracion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAtras.setBackground(new java.awt.Color(121, 127, 139));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atrasBoton.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        org.jdesktop.layout.GroupLayout PContenidoOpcionesLayout = new org.jdesktop.layout.GroupLayout(PContenidoOpciones);
        PContenidoOpciones.setLayout(PContenidoOpcionesLayout);
        PContenidoOpcionesLayout.setHorizontalGroup(
            PContenidoOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PContenidoOpcionesLayout.createSequentialGroup()
                .add(88, 88, 88)
                .add(PContenidoOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnRecargar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .add(PContenidoOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btnSaldo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btnPagar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btnMovimientos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btnVehiculos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btnConfiguracion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)))
                .add(18, 18, 18)
                .add(btnAtras)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PContenidoOpcionesLayout.setVerticalGroup(
            PContenidoOpcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PContenidoOpcionesLayout.createSequentialGroup()
                .add(27, 27, 27)
                .add(btnRecargar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnSaldo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnPagar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnMovimientos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnVehiculos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btnConfiguracion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoOpcionesLayout.createSequentialGroup()
                .addContainerGap(385, Short.MAX_VALUE)
                .add(btnAtras)
                .add(14, 14, 14))
        );

        PGeneralOpciones.add(PContenidoOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 88, 461, 460));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralOpciones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralOpciones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOpcionesIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOpcionesIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOpcionesIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOpcionesIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOpcionesIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PContenidoOpciones;
    private javax.swing.JPanel PGeneralOpciones;
    private javax.swing.JPanel PTituloOpciones;
    private javax.swing.JButton btnAtras;
    public javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnMovimientos;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables

}
