/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Yesenia
 */
public class frmPagar extends javax.swing.JFrame {

    /** Creates new form frmPagar */
    public frmPagar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PGeneralPagar = new javax.swing.JPanel();
        PTituloPagar = new javax.swing.JPanel();
        lblPagar = new javax.swing.JLabel();
        PContenidoPagar = new javax.swing.JPanel();
        lblPeaje = new javax.swing.JLabel();
        cbxPeaje = new javax.swing.JComboBox<>();
        lblEstacion = new javax.swing.JLabel();
        cbxEstacion = new javax.swing.JComboBox<>();
        btnPagar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        txtCosto = new javax.swing.JLabel();
        dcFechaPago = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblFecha1 = new javax.swing.JLabel();
        cbxVehiculo = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblFecha2 = new javax.swing.JLabel();
        lblFecha3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PGeneralPagar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PTituloPagar.setBackground(new java.awt.Color(159, 162, 178));

        lblPagar.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        lblPagar.setText("Pagar peaje");

        org.jdesktop.layout.GroupLayout PTituloPagarLayout = new org.jdesktop.layout.GroupLayout(PTituloPagar);
        PTituloPagar.setLayout(PTituloPagarLayout);
        PTituloPagarLayout.setHorizontalGroup(
            PTituloPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 510, Short.MAX_VALUE)
            .add(PTituloPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(PTituloPagarLayout.createSequentialGroup()
                    .add(111, 111, 111)
                    .add(lblPagar)
                    .addContainerGap(145, Short.MAX_VALUE)))
        );
        PTituloPagarLayout.setVerticalGroup(
            PTituloPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
            .add(PTituloPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(PTituloPagarLayout.createSequentialGroup()
                    .add(26, 26, 26)
                    .add(lblPagar)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );

        PGeneralPagar.add(PTituloPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        PContenidoPagar.setBackground(new java.awt.Color(121, 127, 139));
        PContenidoPagar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeaje.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        lblPeaje.setText("Peaje:");
        PContenidoPagar.add(lblPeaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 77, -1));

        cbxPeaje.setBackground(new java.awt.Color(121, 127, 139));
        cbxPeaje.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxPeaje.setBorder(null);
        cbxPeaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxPeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPeajeActionPerformed(evt);
            }
        });
        PContenidoPagar.add(cbxPeaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 239, -1));

        lblEstacion.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        lblEstacion.setText("Estación:");
        PContenidoPagar.add(lblEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 116, -1));

        cbxEstacion.setBackground(new java.awt.Color(121, 127, 139));
        cbxEstacion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxEstacion.setBorder(null);
        cbxEstacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstacionActionPerformed(evt);
            }
        });
        PContenidoPagar.add(cbxEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 240, -1));

        btnPagar.setBackground(new java.awt.Color(121, 127, 139));
        btnPagar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnPagar.setText("Realizar pago");
        btnPagar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PContenidoPagar.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 150, 45));

        btnAtras.setBackground(new java.awt.Color(121, 127, 139));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atrasBoton.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PContenidoPagar.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));

        txtCosto.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        txtCosto.setText("1.5");
        PContenidoPagar.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 60, 30));

        dcFechaPago.setBackground(new java.awt.Color(121, 127, 139));
        PContenidoPagar.add(dcFechaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 240, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        PContenidoPagar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 60, 240, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        PContenidoPagar.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 240, 10));

        lblFecha1.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        lblFecha1.setText("Vehiculos:");
        PContenidoPagar.add(lblFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 127, -1));

        cbxVehiculo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVehiculoActionPerformed(evt);
            }
        });
        PContenidoPagar.add(cbxVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 240, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        PContenidoPagar.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 240, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        PContenidoPagar.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 240, 10));

        lblFecha2.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        lblFecha2.setText("Fecha:");
        PContenidoPagar.add(lblFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 80, 20));

        lblFecha3.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        lblFecha3.setText("Costo: S/.");
        PContenidoPagar.add(lblFecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 120, 30));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 30, Short.MAX_VALUE)
        );

        PContenidoPagar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 100, 30));

        PGeneralPagar.add(PContenidoPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 99, 510, 540));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralPagar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralPagar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstacionActionPerformed

    private void cbxPeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPeajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPeajeActionPerformed

    private void cbxVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PContenidoPagar;
    private javax.swing.JPanel PGeneralPagar;
    private javax.swing.JPanel PTituloPagar;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnPagar;
    public javax.swing.JComboBox<String> cbxEstacion;
    public javax.swing.JComboBox<String> cbxPeaje;
    public javax.swing.JComboBox<String> cbxVehiculo;
    public com.toedter.calendar.JDateChooser dcFechaPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblEstacion;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblFecha2;
    private javax.swing.JLabel lblFecha3;
    private javax.swing.JLabel lblPagar;
    private javax.swing.JLabel lblPeaje;
    public javax.swing.JLabel txtCosto;
    // End of variables declaration//GEN-END:variables

}
