/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Yesenia
 */
public class frmPagar extends javax.swing.JFrame {

    /** Creates new form frmPagar */
    public frmPagar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PGeneralPagar = new javax.swing.JPanel();
        PTituloPagar = new javax.swing.JPanel();
        lblPagar = new javax.swing.JLabel();
        PContenidoPagar = new javax.swing.JPanel();
        lblPeaje = new javax.swing.JLabel();
        cbxPeaje = new javax.swing.JComboBox<>();
        lblEstacion = new javax.swing.JLabel();
        cbxEstacion = new javax.swing.JComboBox<>();
        btnPagar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        dcFechaPago = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblFecha1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PGeneralPagar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PTituloPagar.setBackground(new java.awt.Color(159, 162, 178));

        lblPagar.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        lblPagar.setForeground(new java.awt.Color(0, 0, 0));
        lblPagar.setText("Pagar peaje");

        org.jdesktop.layout.GroupLayout PTituloPagarLayout = new org.jdesktop.layout.GroupLayout(PTituloPagar);
        PTituloPagar.setLayout(PTituloPagarLayout);
        PTituloPagarLayout.setHorizontalGroup(
            PTituloPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 510, Short.MAX_VALUE)
            .add(PTituloPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(PTituloPagarLayout.createSequentialGroup()
                    .add(111, 111, 111)
                    .add(lblPagar)
                    .addContainerGap(145, Short.MAX_VALUE)))
        );
        PTituloPagarLayout.setVerticalGroup(
            PTituloPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
            .add(PTituloPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(PTituloPagarLayout.createSequentialGroup()
                    .add(26, 26, 26)
                    .add(lblPagar)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );

        PGeneralPagar.add(PTituloPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        PContenidoPagar.setBackground(new java.awt.Color(121, 127, 139));

        lblPeaje.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        lblPeaje.setForeground(new java.awt.Color(0, 0, 0));
        lblPeaje.setText("Peaje:");

        cbxPeaje.setBackground(new java.awt.Color(121, 127, 139));
        cbxPeaje.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxPeaje.setForeground(new java.awt.Color(0, 0, 0));
        cbxPeaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                                  ", "Panamericana Norte", "Panamericana Sur" }));
        cbxPeaje.setBorder(null);
        cbxPeaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblEstacion.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        lblEstacion.setForeground(new java.awt.Color(0, 0, 0));
        lblEstacion.setText("Estación:");

        cbxEstacion.setBackground(new java.awt.Color(121, 127, 139));
        cbxEstacion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxEstacion.setForeground(new java.awt.Color(0, 0, 0));
        cbxEstacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                                          ", "Serpentin de Pasamayo", "Variante de Pasamayo", "El paraíso", "Fortaleza", "Chilca" }));
        cbxEstacion.setBorder(null);
        cbxEstacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnPagar.setBackground(new java.awt.Color(121, 127, 139));
        btnPagar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(0, 0, 0));
        btnPagar.setText("Realizar pago");
        btnPagar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAtras.setBackground(new java.awt.Color(121, 127, 139));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atrasBoton.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblFecha.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha:");

        dcFechaPago.setBackground(new java.awt.Color(121, 127, 139));
        dcFechaPago.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        lblFecha1.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        lblFecha1.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha1.setText("Vehiculos:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.layout.GroupLayout PContenidoPagarLayout = new org.jdesktop.layout.GroupLayout(PContenidoPagar);
        PContenidoPagar.setLayout(PContenidoPagarLayout);
        PContenidoPagarLayout.setHorizontalGroup(
            PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PContenidoPagarLayout.createSequentialGroup()
                .add(72, 72, 72)
                .add(PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoPagarLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(btnAtras)
                        .add(27, 27, 27))
                    .add(PContenidoPagarLayout.createSequentialGroup()
                        .add(PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(PContenidoPagarLayout.createSequentialGroup()
                                .add(lblFecha1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jComboBox1, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(PContenidoPagarLayout.createSequentialGroup()
                                        .add(lblEstacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(cbxEstacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoPagarLayout.createSequentialGroup()
                                        .add(lblPeaje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(51, 51, 51)
                                        .add(PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jSeparator1)
                                            .add(cbxPeaje, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .add(PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(btnPagar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(PContenidoPagarLayout.createSequentialGroup()
                                    .add(lblFecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(18, 18, 18)
                                    .add(dcFechaPago, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(69, Short.MAX_VALUE))))
        );
        PContenidoPagarLayout.setVerticalGroup(
            PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PContenidoPagarLayout.createSequentialGroup()
                .add(50, 50, 50)
                .add(PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblPeaje)
                    .add(cbxPeaje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(34, 34, 34)
                .add(PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblEstacion)
                    .add(cbxEstacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(35, 35, 35)
                .add(PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblFecha1)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(40, 40, 40)
                .add(PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lblFecha)
                    .add(dcFechaPago, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(PContenidoPagarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PContenidoPagarLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnAtras)
                        .add(22, 22, 22))
                    .add(PContenidoPagarLayout.createSequentialGroup()
                        .add(41, 41, 41)
                        .add(btnPagar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(61, Short.MAX_VALUE))))
        );

        PGeneralPagar.add(PContenidoPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 99, 510, 470));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralPagar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralPagar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PContenidoPagar;
    private javax.swing.JPanel PGeneralPagar;
    private javax.swing.JPanel PTituloPagar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cbxEstacion;
    private javax.swing.JComboBox<String> cbxPeaje;
    private com.toedter.calendar.JDateChooser dcFechaPago;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEstacion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblPagar;
    private javax.swing.JLabel lblPeaje;
    // End of variables declaration//GEN-END:variables

}
