/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Yesenia
 */
public class frmRecarga extends javax.swing.JFrame {

    /** Creates new form frmRecarga */
    public frmRecarga() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PGeneralRecarga = new javax.swing.JPanel();
        PTituloRecarga = new javax.swing.JPanel();
        lblTituloRecarga = new javax.swing.JLabel();
        PContenidoRecarga = new javax.swing.JPanel();
        lblMonto = new javax.swing.JLabel();
        lblSimbolo1 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblComprobante = new javax.swing.JLabel();
        btnBoleta = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        lblMedioPago = new javax.swing.JLabel();
        lblDescripcion3 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        dcFechaPago = new com.toedter.calendar.JDateChooser();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PGeneralRecarga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PTituloRecarga.setBackground(new java.awt.Color(159, 162, 178));

        lblTituloRecarga.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        lblTituloRecarga.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloRecarga.setText("Recarga tu PEX");

        org.jdesktop.layout.GroupLayout PTituloRecargaLayout = new org.jdesktop.layout.GroupLayout(PTituloRecarga);
        PTituloRecarga.setLayout(PTituloRecargaLayout);
        PTituloRecargaLayout.setHorizontalGroup(
            PTituloRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PTituloRecargaLayout.createSequentialGroup()
                .add(100, 100, 100)
                .add(lblTituloRecarga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 343, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        PTituloRecargaLayout.setVerticalGroup(
            PTituloRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PTituloRecargaLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .add(lblTituloRecarga)
                .add(28, 28, 28))
        );

        PGeneralRecarga.add(PTituloRecarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        PContenidoRecarga.setBackground(new java.awt.Color(121, 127, 139));

        lblMonto.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(0, 0, 0));
        lblMonto.setText("Monto:");

        lblSimbolo1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSimbolo1.setForeground(new java.awt.Color(0, 0, 0));
        lblSimbolo1.setText("S/");

        txtMonto.setBackground(new java.awt.Color(121, 127, 139));
        txtMonto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(0, 0, 0));
        txtMonto.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblComprobante.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblComprobante.setForeground(new java.awt.Color(0, 0, 0));
        lblComprobante.setText("Comprobante de pago");

        btnBoleta.setBackground(new java.awt.Color(121, 127, 139));
        btnBoleta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBoleta.setForeground(new java.awt.Color(0, 0, 0));
        btnBoleta.setText("Boleta");
        btnBoleta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBoleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnFactura.setBackground(new java.awt.Color(121, 127, 139));
        btnFactura.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnFactura.setForeground(new java.awt.Color(0, 0, 0));
        btnFactura.setText("Factura");
        btnFactura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblMedioPago.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMedioPago.setForeground(new java.awt.Color(0, 0, 0));
        lblMedioPago.setText("Datos de tarjeta");

        lblDescripcion3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblDescripcion3.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion3.setText("Contraseña de la tarjeta");
        lblDescripcion3.setToolTipText("");

        btnAtras.setBackground(new java.awt.Color(121, 127, 139));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atrasBoton.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblFecha.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha:");

        dcFechaPago.setBackground(new java.awt.Color(121, 127, 139));
        dcFechaPago.setForeground(new java.awt.Color(0, 0, 0));

        jPasswordField1.setText("jPasswordField1");

        org.jdesktop.layout.GroupLayout PContenidoRecargaLayout = new org.jdesktop.layout.GroupLayout(PContenidoRecarga);
        PContenidoRecarga.setLayout(PContenidoRecargaLayout);
        PContenidoRecargaLayout.setHorizontalGroup(
            PContenidoRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoRecargaLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .add(PContenidoRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoRecargaLayout.createSequentialGroup()
                        .add(PContenidoRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblComprobante)
                            .add(PContenidoRecargaLayout.createSequentialGroup()
                                .add(22, 22, 22)
                                .add(PContenidoRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblMedioPago)
                                    .add(PContenidoRecargaLayout.createSequentialGroup()
                                        .add(btnBoleta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(26, 26, 26)
                                        .add(btnFactura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(PContenidoRecargaLayout.createSequentialGroup()
                                .add(9, 9, 9)
                                .add(lblDescripcion3)))
                        .add(166, 166, 166))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoRecargaLayout.createSequentialGroup()
                        .add(btnAtras)
                        .add(26, 26, 26))))
            .add(PContenidoRecargaLayout.createSequentialGroup()
                .add(PContenidoRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PContenidoRecargaLayout.createSequentialGroup()
                        .add(149, 149, 149)
                        .add(PContenidoRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblMonto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblFecha))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PContenidoRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(PContenidoRecargaLayout.createSequentialGroup()
                                .add(lblSimbolo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PContenidoRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jSeparator1)
                                    .add(txtMonto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(dcFechaPago, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(PContenidoRecargaLayout.createSequentialGroup()
                        .add(222, 222, 222)
                        .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(0, 0, Short.MAX_VALUE))
        );
        PContenidoRecargaLayout.setVerticalGroup(
            PContenidoRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PContenidoRecargaLayout.createSequentialGroup()
                .add(42, 42, 42)
                .add(PContenidoRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblMonto)
                    .add(lblSimbolo1)
                    .add(txtMonto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33)
                .add(PContenidoRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(dcFechaPago, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblFecha))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 39, Short.MAX_VALUE)
                .add(lblComprobante)
                .add(18, 18, 18)
                .add(PContenidoRecargaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnBoleta, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnFactura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(lblMedioPago)
                .add(18, 18, 18)
                .add(lblDescripcion3)
                .add(18, 18, 18)
                .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(42, 42, 42)
                .add(btnAtras)
                .add(18, 18, 18))
        );

        PGeneralRecarga.add(PContenidoRecarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 104, 550, 520));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralRecarga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralRecarga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRecarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRecarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PContenidoRecarga;
    private javax.swing.JPanel PGeneralRecarga;
    private javax.swing.JPanel PTituloRecarga;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBoleta;
    private javax.swing.JButton btnFactura;
    private com.toedter.calendar.JDateChooser dcFechaPago;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblComprobante;
    private javax.swing.JLabel lblDescripcion3;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMedioPago;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblSimbolo1;
    private javax.swing.JLabel lblTituloRecarga;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

}
