/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Yesenia
 */
public class frmRecargaOpcional extends javax.swing.JFrame {

    /** Creates new form frmRecargaOpcional */
    public frmRecargaOpcional() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PGeneralRecargaOpcional = new javax.swing.JPanel();
        PTituloRecargaOpcional = new javax.swing.JPanel();
        lblTituloRecargaAdicional = new javax.swing.JLabel();
        PContenidoRecargaOpcional = new javax.swing.JPanel();
        lblRelojIcon = new javax.swing.JLabel();
        lblDescripcion1 = new javax.swing.JLabel();
        lblDescripcion2 = new javax.swing.JLabel();
        lblMontoOpcional = new javax.swing.JLabel();
        txtMontoOpcional = new javax.swing.JTextField();
        lblSimbolo1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblComprobante = new javax.swing.JLabel();
        lblMedioPago = new javax.swing.JLabel();
        lblDescripcion3 = new javax.swing.JLabel();
        cbxMedioPago = new javax.swing.JComboBox<>();
        PDatos = new javax.swing.JPanel();
        lblEtiqueta = new javax.swing.JLabel();
        lblSaldoInicial = new javax.swing.JLabel();
        lblRecargaAdicional = new javax.swing.JLabel();
        lblDelivery = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblMontoEtiqueta = new javax.swing.JLabel();
        lblMontoSaldoInicial = new javax.swing.JLabel();
        lblGratis = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblSimbolo2 = new javax.swing.JLabel();
        txtMontoRecarga = new javax.swing.JTextField();
        lblSimbolo3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        cbxComprobantePago = new javax.swing.JComboBox<>();
        lblDescripcion4 = new javax.swing.JLabel();
        txtNumeroTarjeta = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblDescripcion5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtClaveTarjeta = new javax.swing.JPasswordField();
        lblDescripcion6 = new javax.swing.JLabel();
        dcFechaVencimiento = new com.toedter.calendar.JDateChooser();
        lblDescripcion7 = new javax.swing.JLabel();
        txtCVV = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PGeneralRecargaOpcional.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PTituloRecargaOpcional.setBackground(new java.awt.Color(159, 162, 178));

        lblTituloRecargaAdicional.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        lblTituloRecargaAdicional.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloRecargaAdicional.setText("Recarga adicional (opcional)");

        org.jdesktop.layout.GroupLayout PTituloRecargaOpcionalLayout = new org.jdesktop.layout.GroupLayout(PTituloRecargaOpcional);
        PTituloRecargaOpcional.setLayout(PTituloRecargaOpcionalLayout);
        PTituloRecargaOpcionalLayout.setHorizontalGroup(
            PTituloRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PTituloRecargaOpcionalLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .add(lblTituloRecargaAdicional)
                .add(65, 65, 65))
        );
        PTituloRecargaOpcionalLayout.setVerticalGroup(
            PTituloRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PTituloRecargaOpcionalLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(lblTituloRecargaAdicional)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        PGeneralRecargaOpcional.add(PTituloRecargaOpcional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 110));

        PContenidoRecargaOpcional.setBackground(new java.awt.Color(121, 127, 139));

        lblRelojIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reloj.png"))); // NOI18N

        lblDescripcion1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblDescripcion1.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion1.setText("¡AHORRA TIEMPO RECARGANDO AHORA!");

        lblDescripcion2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDescripcion2.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion2.setText("Evita tener que preocuparte por recargar pronto.\t");

        lblMontoOpcional.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        lblMontoOpcional.setForeground(new java.awt.Color(0, 0, 0));
        lblMontoOpcional.setText("Monto:");

        txtMontoOpcional.setBackground(new java.awt.Color(121, 127, 139));
        txtMontoOpcional.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMontoOpcional.setForeground(new java.awt.Color(0, 0, 0));
        txtMontoOpcional.setBorder(null);

        lblSimbolo1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSimbolo1.setForeground(new java.awt.Color(0, 0, 0));
        lblSimbolo1.setText("S/");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblComprobante.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblComprobante.setForeground(new java.awt.Color(0, 0, 0));
        lblComprobante.setText("Comprobante de pago");

        lblMedioPago.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMedioPago.setForeground(new java.awt.Color(0, 0, 0));
        lblMedioPago.setText("Medio de pago");

        lblDescripcion3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblDescripcion3.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion3.setText("Elija su medio de pago");
        lblDescripcion3.setToolTipText("");

        cbxMedioPago.setBackground(new java.awt.Color(121, 127, 139));
        cbxMedioPago.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxMedioPago.setForeground(new java.awt.Color(0, 0, 0));
        cbxMedioPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                                  ", "Visa (Crédito o débito)", "Master Card (Crédito o débito)", "American Express (Crédito)", "Diners Club (Crédito)", " " }));
        cbxMedioPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PDatos.setBackground(new java.awt.Color(121, 127, 153));
        PDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PDatos.setEnabled(false);

        lblEtiqueta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEtiqueta.setForeground(new java.awt.Color(0, 0, 0));
        lblEtiqueta.setText("Etiqueta PEX");

        lblSaldoInicial.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSaldoInicial.setForeground(new java.awt.Color(0, 0, 0));
        lblSaldoInicial.setText("Saldo inicial");

        lblRecargaAdicional.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblRecargaAdicional.setForeground(new java.awt.Color(0, 0, 0));
        lblRecargaAdicional.setText("Recarga adicional");

        lblDelivery.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDelivery.setForeground(new java.awt.Color(0, 0, 0));
        lblDelivery.setText("Delivery");

        lblTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("TOTAL");

        lblMontoEtiqueta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMontoEtiqueta.setForeground(new java.awt.Color(0, 0, 0));
        lblMontoEtiqueta.setText("S/ 8.00");

        lblMontoSaldoInicial.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMontoSaldoInicial.setForeground(new java.awt.Color(0, 0, 0));
        lblMontoSaldoInicial.setText("S/ 12.00");

        lblGratis.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblGratis.setForeground(new java.awt.Color(0, 0, 0));
        lblGratis.setText("Gratis");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        lblSimbolo2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSimbolo2.setForeground(new java.awt.Color(0, 0, 0));
        lblSimbolo2.setText("S/");

        txtMontoRecarga.setBackground(new java.awt.Color(121, 127, 153));
        txtMontoRecarga.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMontoRecarga.setForeground(new java.awt.Color(0, 0, 0));
        txtMontoRecarga.setBorder(null);
        txtMontoRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoRecargaActionPerformed(evt);
            }
        });

        lblSimbolo3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSimbolo3.setForeground(new java.awt.Color(0, 0, 0));
        lblSimbolo3.setText("S/");

        txtTotal.setBackground(new java.awt.Color(121, 127, 153));
        txtTotal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 0, 0));
        txtTotal.setBorder(null);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(159, 162, 178));
        btnCalcular.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcular.setText("Calcular Total");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PDatosLayout = new org.jdesktop.layout.GroupLayout(PDatos);
        PDatos.setLayout(PDatosLayout);
        PDatosLayout.setHorizontalGroup(
            PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PDatosLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, PDatosLayout.createSequentialGroup()
                        .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblEtiqueta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblDelivery, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblSaldoInicial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblRecargaAdicional, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PDatosLayout.createSequentialGroup()
                                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblMontoEtiqueta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblMontoSaldoInicial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblGratis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(0, 0, Short.MAX_VALUE))
                            .add(PDatosLayout.createSequentialGroup()
                                .add(lblSimbolo2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(txtMontoRecarga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, PDatosLayout.createSequentialGroup()
                        .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, PDatosLayout.createSequentialGroup()
                                .add(lblTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(lblSimbolo3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(PDatosLayout.createSequentialGroup()
                .add(83, 83, 83)
                .add(btnCalcular)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PDatosLayout.setVerticalGroup(
            PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PDatosLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnCalcular)
                .add(18, 18, 18)
                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblEtiqueta)
                    .add(lblMontoEtiqueta))
                .add(18, 18, 18)
                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblSaldoInicial)
                    .add(lblMontoSaldoInicial))
                .add(18, 18, 18)
                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblRecargaAdicional)
                    .add(txtMontoRecarga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblSimbolo2))
                .add(18, 18, 18)
                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblDelivery)
                    .add(lblGratis))
                .add(18, 18, 18)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(txtTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(lblSimbolo3))
                    .add(lblTotal))
                .add(20, 20, 20))
        );

        cbxComprobantePago.setBackground(new java.awt.Color(121, 127, 139));
        cbxComprobantePago.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxComprobantePago.setForeground(new java.awt.Color(0, 0, 0));
        cbxComprobantePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "           ", "Boleta", "Factura", " " }));
        cbxComprobantePago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblDescripcion4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblDescripcion4.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion4.setText("Digite su número de tarjeta");
        lblDescripcion4.setToolTipText("");

        txtNumeroTarjeta.setBackground(new java.awt.Color(121, 127, 139));
        txtNumeroTarjeta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNumeroTarjeta.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroTarjeta.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        lblDescripcion5.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblDescripcion5.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion5.setText("Clave de tarjeta");
        lblDescripcion5.setToolTipText("");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        txtClaveTarjeta.setBackground(new java.awt.Color(121, 127, 139));
        txtClaveTarjeta.setBorder(null);

        lblDescripcion6.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblDescripcion6.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion6.setText("Fecha de vencimiento de la tarjeta");
        lblDescripcion6.setToolTipText("");

        lblDescripcion7.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblDescripcion7.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion7.setText("CVV");
        lblDescripcion7.setToolTipText("");

        txtCVV.setBackground(new java.awt.Color(121, 127, 139));
        txtCVV.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        btnFinalizar.setBackground(new java.awt.Color(121, 127, 153));
        btnFinalizar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        btnFinalizar.setText("Finalizar");
        btnFinalizar.setToolTipText("");
        btnFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PContenidoRecargaOpcionalLayout = new org.jdesktop.layout.GroupLayout(PContenidoRecargaOpcional);
        PContenidoRecargaOpcional.setLayout(PContenidoRecargaOpcionalLayout);
        PContenidoRecargaOpcionalLayout.setHorizontalGroup(
            PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                .add(74, 74, 74)
                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                        .add(lblRelojIcon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(27, 27, 27)
                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblDescripcion1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 486, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblDescripcion2))
                        .addContainerGap(87, Short.MAX_VALUE))
                    .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(dcFechaVencimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblDescripcion6))
                                .add(83, 83, 83)
                                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator5)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, txtCVV, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(lblDescripcion7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(0, 0, Short.MAX_VALUE))
                            .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                            .add(lblMontoOpcional, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                                    .add(lblSimbolo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                    .add(txtMontoOpcional, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(jSeparator1)))
                                        .add(lblComprobante, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(cbxComprobantePago, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(lblMedioPago, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 218, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(lblDescripcion3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 179, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(cbxMedioPago, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 243, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(lblDescripcion4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, txtNumeroTarjeta)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblDescripcion5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(PDatos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator4)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, txtClaveTarjeta, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(btnFinalizar)
                                .add(9, 9, 9)))
                        .add(25, 25, 25))))
        );
        PContenidoRecargaOpcionalLayout.setVerticalGroup(
            PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblRelojIcon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                        .add(13, 13, 13)
                        .add(lblDescripcion1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblDescripcion2)))
                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                        .add(37, 37, 37)
                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblMontoOpcional)
                            .add(txtMontoOpcional, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblSimbolo1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(30, 30, 30)
                        .add(lblComprobante)
                        .add(18, 18, 18)
                        .add(cbxComprobantePago, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(lblMedioPago)
                        .add(18, 18, 18)
                        .add(lblDescripcion3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(cbxMedioPago, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoRecargaOpcionalLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PDatos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(19, 19, 19)))
                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblDescripcion4)
                    .add(lblDescripcion5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(txtNumeroTarjeta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtClaveTarjeta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblDescripcion6)
                    .add(lblDescripcion7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dcFechaVencimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                        .add(txtCVV, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 9, Short.MAX_VALUE)
                .add(btnFinalizar)
                .add(25, 25, 25))
        );

        PGeneralRecargaOpcional.add(PContenidoRecargaOpcional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 749, 610));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralRecargaOpcional, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralRecargaOpcional, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoRecargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoRecargaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRecargaOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRecargaOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRecargaOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRecargaOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRecargaOpcional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PContenidoRecargaOpcional;
    private javax.swing.JPanel PDatos;
    private javax.swing.JPanel PGeneralRecargaOpcional;
    private javax.swing.JPanel PTituloRecargaOpcional;
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnFinalizar;
    public javax.swing.JComboBox<String> cbxComprobantePago;
    public javax.swing.JComboBox<String> cbxMedioPago;
    public com.toedter.calendar.JDateChooser dcFechaVencimiento;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblComprobante;
    private javax.swing.JLabel lblDelivery;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblDescripcion2;
    private javax.swing.JLabel lblDescripcion3;
    private javax.swing.JLabel lblDescripcion4;
    private javax.swing.JLabel lblDescripcion5;
    private javax.swing.JLabel lblDescripcion6;
    private javax.swing.JLabel lblDescripcion7;
    private javax.swing.JLabel lblEtiqueta;
    private javax.swing.JLabel lblGratis;
    private javax.swing.JLabel lblMedioPago;
    private javax.swing.JLabel lblMontoEtiqueta;
    private javax.swing.JLabel lblMontoOpcional;
    private javax.swing.JLabel lblMontoSaldoInicial;
    private javax.swing.JLabel lblRecargaAdicional;
    private javax.swing.JLabel lblRelojIcon;
    private javax.swing.JLabel lblSaldoInicial;
    private javax.swing.JLabel lblSimbolo1;
    private javax.swing.JLabel lblSimbolo2;
    private javax.swing.JLabel lblSimbolo3;
    private javax.swing.JLabel lblTituloRecargaAdicional;
    private javax.swing.JLabel lblTotal;
    public javax.swing.JPasswordField txtCVV;
    public javax.swing.JPasswordField txtClaveTarjeta;
    public javax.swing.JTextField txtMontoOpcional;
    public javax.swing.JTextField txtMontoRecarga;
    public javax.swing.JTextField txtNumeroTarjeta;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
