/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.text.SimpleDateFormat;
import java.awt.Color;

/**
 *
 * @author Yesenia
 */
public class frmRecargaOpcional extends javax.swing.JFrame {

    /** Creates new form frmRecargaOpcional */
    private int opcionComprobantePago;
    public frmRecargaOpcional() {
        initComponents();
        this.opcionComprobantePago = 0;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PGeneralRecargaOpcional = new javax.swing.JPanel();
        PTituloRecargaOpcional = new javax.swing.JPanel();
        lblTituloRecargaAdicional = new javax.swing.JLabel();
        PContenidoRecargaOpcional = new javax.swing.JPanel();
        lblRelojIcon = new javax.swing.JLabel();
        lblDescripcion1 = new javax.swing.JLabel();
        lblDescripcion2 = new javax.swing.JLabel();
        lblMontoOpcional = new javax.swing.JLabel();
        txtMontoOpcional = new javax.swing.JTextField();
        lblSimbolo1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblComprobante = new javax.swing.JLabel();
        lblMedioPago = new javax.swing.JLabel();
        lblDescripcion3 = new javax.swing.JLabel();
        cbxMedioPago = new javax.swing.JComboBox<>();
        lblDescripcion4 = new javax.swing.JLabel();
        txtNumeroTarjeta = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblDescripcion6 = new javax.swing.JLabel();
        lblDescripcion7 = new javax.swing.JLabel();
        txtCVV = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        btnFinalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        PDatos = new javax.swing.JPanel();
        lblEtiqueta = new javax.swing.JLabel();
        lblSaldoInicial = new javax.swing.JLabel();
        lblRecargaAdicional = new javax.swing.JLabel();
        lblDelivery = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblMontoEtiqueta = new javax.swing.JLabel();
        lblMontoSaldoInicial = new javax.swing.JLabel();
        lblGratis = new javax.swing.JLabel();
        lblSimbolo2 = new javax.swing.JLabel();
        txtMontoRecarga = new javax.swing.JTextField();
        lblSimbolo3 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtTotal = new javax.swing.JTextField();
        btnFactura = new javax.swing.JButton();
        btnBoleta = new javax.swing.JButton();
        jycAñoVencimiento = new com.toedter.calendar.JYearChooser();
        jmcMesVencimiento = new com.toedter.calendar.JMonthChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PGeneralRecargaOpcional.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PTituloRecargaOpcional.setBackground(new java.awt.Color(159, 162, 178));

        lblTituloRecargaAdicional.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        lblTituloRecargaAdicional.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloRecargaAdicional.setText("Recarga adicional ");

        org.jdesktop.layout.GroupLayout PTituloRecargaOpcionalLayout = new org.jdesktop.layout.GroupLayout(PTituloRecargaOpcional);
        PTituloRecargaOpcional.setLayout(PTituloRecargaOpcionalLayout);
        PTituloRecargaOpcionalLayout.setHorizontalGroup(
            PTituloRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PTituloRecargaOpcionalLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .add(lblTituloRecargaAdicional)
                .add(167, 167, 167))
        );
        PTituloRecargaOpcionalLayout.setVerticalGroup(
            PTituloRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PTituloRecargaOpcionalLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(lblTituloRecargaAdicional)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        PGeneralRecargaOpcional.add(PTituloRecargaOpcional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 110));

        PContenidoRecargaOpcional.setBackground(new java.awt.Color(121, 127, 139));

        lblRelojIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reloj.png"))); // NOI18N

        lblDescripcion1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblDescripcion1.setText("¡AHORRA TIEMPO RECARGANDO AHORA!");

        lblDescripcion2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDescripcion2.setText("Evita tener que preocuparte por recargar pronto.\t");

        lblMontoOpcional.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        lblMontoOpcional.setText("Monto:");

        txtMontoOpcional.setBackground(new java.awt.Color(121, 127, 139));
        txtMontoOpcional.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMontoOpcional.setBorder(null);

        lblSimbolo1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSimbolo1.setText("S/");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblComprobante.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblComprobante.setText("Comprobante de pago");

        lblMedioPago.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMedioPago.setText("Medio de pago");

        lblDescripcion3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblDescripcion3.setText("Elija su medio de pago");
        lblDescripcion3.setToolTipText("");

        cbxMedioPago.setBackground(new java.awt.Color(121, 127, 139));
        cbxMedioPago.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxMedioPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                                   ", "VISA", "MASTER CARD", "AMERICAN EXPRESS", "DINERS CLUB", " " }));
        cbxMedioPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblDescripcion4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblDescripcion4.setText("Digite su número de tarjeta");
        lblDescripcion4.setToolTipText("");

        txtNumeroTarjeta.setBackground(new java.awt.Color(121, 127, 139));
        txtNumeroTarjeta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNumeroTarjeta.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        lblDescripcion6.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblDescripcion6.setText("Fecha de vencimiento de la tarjeta");
        lblDescripcion6.setToolTipText("");

        lblDescripcion7.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        lblDescripcion7.setText("CVV");
        lblDescripcion7.setToolTipText("");

        txtCVV.setBackground(new java.awt.Color(121, 127, 139));
        txtCVV.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        btnFinalizar.setBackground(new java.awt.Color(121, 127, 153));
        btnFinalizar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.setToolTipText("");
        btnFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        jTextPane1.setBackground(new java.awt.Color(121, 127, 139));
        jTextPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane1.setText("Inicialmente cuenta con un saldo de S/ 12.00 en su cuenta PEX.\nSi desea recargar con un monto extra digítelo a continuación. ");
        jScrollPane1.setViewportView(jTextPane1);

        PDatos.setBackground(new java.awt.Color(121, 127, 153));
        PDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PDatos.setEnabled(false);

        lblEtiqueta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEtiqueta.setForeground(new java.awt.Color(0, 0, 0));
        lblEtiqueta.setText("Etiqueta PEX");

        lblSaldoInicial.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSaldoInicial.setForeground(new java.awt.Color(0, 0, 0));
        lblSaldoInicial.setText("Saldo inicial");

        lblRecargaAdicional.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblRecargaAdicional.setForeground(new java.awt.Color(0, 0, 0));
        lblRecargaAdicional.setText("Recarga adicional");

        lblDelivery.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDelivery.setForeground(new java.awt.Color(0, 0, 0));
        lblDelivery.setText("Delivery");

        lblTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("TOTAL");

        lblMontoEtiqueta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMontoEtiqueta.setForeground(new java.awt.Color(0, 0, 0));
        lblMontoEtiqueta.setText("S/ 8.00");

        lblMontoSaldoInicial.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMontoSaldoInicial.setForeground(new java.awt.Color(0, 0, 0));
        lblMontoSaldoInicial.setText("S/ 12.00");

        lblGratis.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblGratis.setForeground(new java.awt.Color(0, 0, 0));
        lblGratis.setText("Gratis");

        lblSimbolo2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSimbolo2.setForeground(new java.awt.Color(0, 0, 0));
        lblSimbolo2.setText("S/");

        txtMontoRecarga.setBackground(new java.awt.Color(121, 127, 153));
        txtMontoRecarga.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMontoRecarga.setBorder(null);
        txtMontoRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoRecargaActionPerformed(evt);
            }
        });

        lblSimbolo3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSimbolo3.setForeground(new java.awt.Color(0, 0, 0));
        lblSimbolo3.setText("S/");

        btnCalcular.setBackground(new java.awt.Color(159, 162, 178));
        btnCalcular.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcular.setText("Calcular Total");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        txtTotal.setBackground(new java.awt.Color(121, 127, 153));
        txtTotal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotal.setBorder(null);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PDatosLayout = new org.jdesktop.layout.GroupLayout(PDatos);
        PDatos.setLayout(PDatosLayout);
        PDatosLayout.setHorizontalGroup(
            PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PDatosLayout.createSequentialGroup()
                .add(83, 83, 83)
                .add(btnCalcular)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(PDatosLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PDatosLayout.createSequentialGroup()
                        .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 244, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(PDatosLayout.createSequentialGroup()
                        .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblEtiqueta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblDelivery, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblSaldoInicial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblRecargaAdicional, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lblMontoEtiqueta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lblMontoSaldoInicial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lblGratis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, PDatosLayout.createSequentialGroup()
                                .add(lblSimbolo2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtMontoRecarga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, PDatosLayout.createSequentialGroup()
                                .add(lblSimbolo3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(13, Short.MAX_VALUE))))
        );
        PDatosLayout.setVerticalGroup(
            PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PDatosLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnCalcular)
                .add(18, 18, 18)
                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblEtiqueta)
                    .add(lblMontoEtiqueta))
                .add(18, 18, 18)
                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblSaldoInicial)
                    .add(lblMontoSaldoInicial))
                .add(18, 18, 18)
                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblRecargaAdicional)
                    .add(txtMontoRecarga, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblSimbolo2))
                .add(18, 18, 18)
                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblDelivery)
                    .add(lblGratis))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(lblSimbolo3)
                        .add(txtTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(lblTotal))
                .add(14, 14, 14))
        );

        btnFactura.setBackground(new java.awt.Color(22, 38, 46));
        btnFactura.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnFactura.setText("Factura");
        btnFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturaMouseClicked(evt);
            }
        });
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        btnBoleta.setBackground(new java.awt.Color(22, 38, 46));
        btnBoleta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBoleta.setForeground(new java.awt.Color(255, 255, 255));
        btnBoleta.setText("Boleta");
        btnBoleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBoletaMouseClicked(evt);
            }
        });
        btnBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletaActionPerformed(evt);
            }
        });

        jycAñoVencimiento.setBackground(new java.awt.Color(121, 127, 139));

        jmcMesVencimiento.setForeground(new java.awt.Color(0, 0, 0));

        org.jdesktop.layout.GroupLayout PContenidoRecargaOpcionalLayout = new org.jdesktop.layout.GroupLayout(PContenidoRecargaOpcional);
        PContenidoRecargaOpcional.setLayout(PContenidoRecargaOpcionalLayout);
        PContenidoRecargaOpcionalLayout.setHorizontalGroup(
            PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                .add(74, 74, 74)
                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                        .add(lblRelojIcon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(27, 27, 27)
                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblDescripcion1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 486, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblDescripcion2))
                        .addContainerGap(88, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PContenidoRecargaOpcionalLayout.createSequentialGroup()
                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblDescripcion6)
                                    .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                        .add(jmcMesVencimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(jycAñoVencimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(83, 83, 83)
                                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator5)
                                    .add(txtCVV, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .add(lblDescripcion7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(btnFinalizar))
                            .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 295, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                        .add(lblMontoOpcional, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                                .add(lblSimbolo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(txtMontoOpcional, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(lblComprobante, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                            .add(btnBoleta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(btnFactura))))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(PDatos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(34, 34, 34))
                    .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblDescripcion4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblMedioPago, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 218, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblDescripcion3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 179, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(cbxMedioPago, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 243, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, txtNumeroTarjeta)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE))))
        );
        PContenidoRecargaOpcionalLayout.setVerticalGroup(
            PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblRelojIcon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                .add(13, 13, 13)
                                .add(lblDescripcion1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(lblDescripcion2)))
                        .add(28, 28, 28)
                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(lblMontoOpcional)
                                    .add(txtMontoOpcional, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblSimbolo1))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(lblComprobante)
                                .add(18, 18, 18)
                                .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(btnFactura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(btnBoleta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(32, 32, 32)
                                .add(lblMedioPago)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(lblDescripcion3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cbxMedioPago, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(lblDescripcion4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(txtNumeroTarjeta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 37, Short.MAX_VALUE))
                            .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                                .add(PDatos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblDescripcion6)
                            .add(lblDescripcion7))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtCVV, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btnFinalizar))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(PContenidoRecargaOpcionalLayout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(PContenidoRecargaOpcionalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jmcMesVencimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jycAñoVencimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(148, 148, 148))
        );

        PGeneralRecargaOpcional.add(PContenidoRecargaOpcional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 750, 660));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralRecargaOpcional, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralRecargaOpcional, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void txtMontoRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoRecargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoRecargaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturaMouseClicked

    }//GEN-LAST:event_btnFacturaMouseClicked

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        btnFactura.setBackground(new Color(64,103,105));
        btnBoleta.setBackground(new Color(22,38,46));
        this.opcionComprobantePago=1;
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnBoletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoletaMouseClicked
        btnBoleta.setBackground(new Color(64,103,105));
        btnFactura.setBackground(new Color(22,38,46));
        this.opcionComprobantePago=2;
    }//GEN-LAST:event_btnBoletaMouseClicked

    private void btnBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBoletaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRecargaOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRecargaOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRecargaOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRecargaOpcional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRecargaOpcional().setVisible(true);
            }
        });
    }

    public int getOpcionComprobantePago() {
        return opcionComprobantePago;
    }

    public void setOpcionComprobantePago(int opcionComprobantePago) {
        this.opcionComprobantePago = opcionComprobantePago;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PContenidoRecargaOpcional;
    private javax.swing.JPanel PDatos;
    private javax.swing.JPanel PGeneralRecargaOpcional;
    private javax.swing.JPanel PTituloRecargaOpcional;
    public javax.swing.JButton btnBoleta;
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnFactura;
    public javax.swing.JButton btnFinalizar;
    public javax.swing.JComboBox<String> cbxMedioPago;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextPane jTextPane1;
    public com.toedter.calendar.JMonthChooser jmcMesVencimiento;
    public com.toedter.calendar.JYearChooser jycAñoVencimiento;
    private javax.swing.JLabel lblComprobante;
    private javax.swing.JLabel lblDelivery;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblDescripcion2;
    private javax.swing.JLabel lblDescripcion3;
    private javax.swing.JLabel lblDescripcion4;
    private javax.swing.JLabel lblDescripcion6;
    private javax.swing.JLabel lblDescripcion7;
    private javax.swing.JLabel lblEtiqueta;
    private javax.swing.JLabel lblGratis;
    private javax.swing.JLabel lblMedioPago;
    private javax.swing.JLabel lblMontoEtiqueta;
    private javax.swing.JLabel lblMontoOpcional;
    private javax.swing.JLabel lblMontoSaldoInicial;
    private javax.swing.JLabel lblRecargaAdicional;
    private javax.swing.JLabel lblRelojIcon;
    private javax.swing.JLabel lblSaldoInicial;
    private javax.swing.JLabel lblSimbolo1;
    private javax.swing.JLabel lblSimbolo2;
    private javax.swing.JLabel lblSimbolo3;
    private javax.swing.JLabel lblTituloRecargaAdicional;
    private javax.swing.JLabel lblTotal;
    public javax.swing.JPasswordField txtCVV;
    public javax.swing.JTextField txtMontoOpcional;
    public javax.swing.JTextField txtMontoRecarga;
    public javax.swing.JTextField txtNumeroTarjeta;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
