/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Yesenia
 */
public class frmSaldo extends javax.swing.JFrame {

    /** Creates new form frmSaldo */
    public frmSaldo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PGeneralSaldo = new javax.swing.JPanel();
        lblDescripcionSaldo = new javax.swing.JLabel();
        lblSimbolo1 = new javax.swing.JLabel();
        txtSaldoTotal = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PGeneralSaldo.setBackground(new java.awt.Color(121, 127, 139));

        lblDescripcionSaldo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblDescripcionSaldo.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcionSaldo.setText("Usted cuenta con un saldo de:");

        lblSimbolo1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblSimbolo1.setForeground(new java.awt.Color(0, 0, 0));
        lblSimbolo1.setText("S/");

        txtSaldoTotal.setBackground(new java.awt.Color(121, 127, 139));
        txtSaldoTotal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSaldoTotal.setForeground(new java.awt.Color(0, 0, 0));
        txtSaldoTotal.setBorder(null);

        btnAtras.setBackground(new java.awt.Color(121, 127, 139));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atrasBoton.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        org.jdesktop.layout.GroupLayout PGeneralSaldoLayout = new org.jdesktop.layout.GroupLayout(PGeneralSaldo);
        PGeneralSaldo.setLayout(PGeneralSaldoLayout);
        PGeneralSaldoLayout.setHorizontalGroup(
            PGeneralSaldoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralSaldoLayout.createSequentialGroup()
                .add(PGeneralSaldoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PGeneralSaldoLayout.createSequentialGroup()
                        .add(54, 54, 54)
                        .add(lblDescripcionSaldo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 303, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(PGeneralSaldoLayout.createSequentialGroup()
                        .add(105, 105, 105)
                        .add(lblSimbolo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(txtSaldoTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PGeneralSaldoLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(btnAtras)
                .add(16, 16, 16))
        );
        PGeneralSaldoLayout.setVerticalGroup(
            PGeneralSaldoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralSaldoLayout.createSequentialGroup()
                .add(41, 41, 41)
                .add(lblDescripcionSaldo)
                .add(31, 31, 31)
                .add(PGeneralSaldoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblSimbolo1)
                    .add(txtSaldoTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 70, Short.MAX_VALUE)
                .add(btnAtras)
                .add(16, 16, 16))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralSaldo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PGeneralSaldo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PGeneralSaldo;
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel lblDescripcionSaldo;
    private javax.swing.JLabel lblSimbolo1;
    private javax.swing.JTextField txtSaldoTotal;
    // End of variables declaration//GEN-END:variables

}
